development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9facec62605b78ca8b72a9f6e6fb03a4@soldierfish.redistogo.com:10637/
  channel_prefix: everybodypaint_production
